#!/bin/sh
if [ -z "$LEDGER_FILE" ]; then
  echo "ERROR: \$LEDGER_FILE not set"
  exit 1
fi
cd "$(dirname "$LEDGER_FILE")"
output="$(ledger entry "$@")"
ledger_result=$?
if [ -z "$output" ]; then
  echo "ERROR: ledger output is empty"
  exit 1
fi
echo "$output"; echo
if [ $ledger_result -ne 0 ]; then
  echo "ERROR: running ledger failed"
  exit 1
fi
read -p "good? [y] " answer
if [ -z "$answer" ] || [ "$answer" == "y" ]; then
  (echo; echo "$output") >> "$LEDGER_FILE"
else
  exit 1
fi
